# Website settings
website:
  title: "Stefano Grassi"
  navbar:
    pinned: true
    right:
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd

  search: false

# Page-footer settings
page-footer:
  left: |
    <span class="faux-block">&#169; {year} Stefano Grassi | All Rights Reserved</span>
  right: |
    <a href="mailto:your-email@example.com">Contact</a> | <a href="privacy.qmd">Privacy Policy</a>

# Project settings
project:
  type: website
  output-dir: docs

# Homepage content file (create index.qmd)
format:
  html:
    fontsize: 1.1em
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
